---
title: "exercise-8"
output: md_document
---

## REading in data files

```{r}
cocoli_data <- read.table("~/Desktop/eeb-177/class-assignments/classwork-tues-2-21-17/cocoli.txt", header = TRUE)

cocoli_data
sizes_in_94 <- cocoli_data$dbh1
names(sizes_in_94) <- cocoli_data$tag
sizes_in_94[1]
sizes_in_94["000001"]
sizes_in_94[c("000009", "000099")]
sizes_in_97 <- cocoli_data$dbh2
rgr_1 <- ((sizes_in_97 - sizes_in_94) / sizes_in_94) / 3
rgr_1

cocoli_data$rgr1 <- rgr_1
cocoli_data
```


## Plotting

```{r}
#bar graphs -> barplot()
#boxplot()
#scatter plots -> plot()
#histogram -> hist()

hist(sizes_in_94, xlab = "DBH (mm)", main = "Distribution of tree sizes in Cocoli(1994)")

plot(x = sizes_in_94, y = sizes_in_97, main = "Scatterplot of sizes", xlab = "Size in 1994 (mm)", ylab = "Size in 1997 (mm)", pch = 19, col = "dark blue", log = "xy")


```


```{r}
library(dplyr)


# %>% is identical to | in terminal
cocoli_data %>% filter(dbh1 > 0) %>% select(dbh1)

cocoli_data %>% filter(dbh1 > 0) %>% arrange(dbh1)

cocoli_data %>% filter(dbh1 > 0) %>% arrange(-dbh1) %>% select(spcode)

cocoli_data %>% filter(dbh1 > 0) %>% group_by(spcode) %>% summarize(mean_dbh_1994 = mean(dbh1))
```




```{r}
housing <- read.csv("Rgraphics/dataSets/landdata-states.csv")
head(housing[1:5])
hist(housing$Home.Value)

library(ggplot2)
ggplot(housing, aes(x = Home.Value)) + geom_histogram()
```


```{r}
plot(Home.Value ~ Date,
     data=subset(housing, State == "MA"))
points(Home.Value ~ Date, col="red", data=subset(housing, State == "TX"))
legend(1975, 400000, c("MA", "TX"), title="State", col=c("black", "red"), pch=c(1, 1))



```

```{r}
ggplot(subset(housing, State %in% c("MA", "TX")),
       aes(x=Date,
           y=Home.Value,
           color=State))+
  geom_point()
```



```{r}
hp2001Q1 <- subset(housing, Date == 2001.25) 
ggplot(hp2001Q1,
       aes(y = Structure.Cost, x = Land.Value)) +
  geom_point()
```



```{r}
ggplot(hp2001Q1,
       aes(y = Structure.Cost, x = log(Land.Value))) +
  geom_point()
```




```{r}
hp2001Q1$pred.SC <- predict(lm(Structure.Cost ~ log(Land.Value), data = hp2001Q1))

p1 <- ggplot(hp2001Q1, aes(x = log(Land.Value), y = Structure.Cost))

p1 + geom_point(aes(color = Home.Value)) +
  geom_line(aes(y = pred.SC))
```



```{r}
p1 +
  geom_point(aes(color = Home.Value)) +
  geom_smooth()
```



```{r}
p1 + 
  geom_text(aes(label=State), size = 3)
```




```{r}
install.packages("ggrepel") 
library("ggrepel")
p1 + 
  geom_point() + 
  geom_text_repel(aes(label=State), size = 3)
```


```{r}
p1 +
  geom_point(aes(size = 2),# incorrect! 2 is not a variable
             color="red") # this is fine -- all points red
```



```{r}
p1 +
  geom_point(aes(color=Home.Value, shape = region))
```


## Exercise 1
```{r}
dat <- read.csv("Rgraphics/dataSets/EconomistData.csv")
head(dat)

ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point()
```


```{r}
args(geom_histogram)
args(stat_bin)
```



```{r}
p2 <- ggplot(housing, aes(x = Home.Value))
p2 + geom_histogram()
```
```{r}
p2 + geom_histogram(stat = "bin", binwidth=4000)
```


```{r}
housing.sum <- aggregate(housing["Home.Value"], housing["State"], FUN=mean)
rbind(head(housing.sum), tail(housing.sum))
```



```{r}
ggplot(housing.sum, aes(x=State, y=Home.Value)) + 
  geom_bar(stat="identity")
```



## Exercise 2
```{r}
p3 <- ggplot(housing,
             aes(x = State,
                 y = Home.Price.Index)) + 
        theme(legend.position="top",
              axis.text=element_text(size = 6))
(p4 <- p3 + geom_point(aes(color = Date),
                       alpha = 0.5,
                       size = 1.5,
                       position = position_jitter(width = 0.25, height = 0)))
```


```{r}
p4 + scale_x_discrete(name="State Abbreviation") +
  scale_color_continuous(name="",
                         breaks = c(1976, 1994, 2013),
                         labels = c("'76", "'94", "'13"))
```



```{r}
p4 +
  scale_x_discrete(name="State Abbreviation") +
  scale_color_continuous(name="",
                         breaks = c(1976, 1994, 2013),
                         labels = c("'76", "'94", "'13"),
                         low = "blue", high = "red")
```
```{r}
p4 +
  scale_color_continuous(name="",
                         breaks = c(1976, 1994, 2013),
                         labels = c("'76", "'94", "'13"),
                         low = "dark blue", high = "dark red")
```


```{r}
p4 +
  scale_color_gradient2(name="",
                        breaks = c(1976, 1994, 2013),
                        labels = c("'76", "'94", "'13"),
                        low = "dark blue",
                        high = "dark red",
                        mid = "gray60",
                        midpoint = 1994)
```


## Exercise 3
```{r}
p5 <- ggplot(housing, aes(x = Date, y = Home.Value))
p5 + geom_line(aes(color = State))
```
```{r}
(p5 <- p5 + geom_line() +
   facet_wrap(~State, ncol = 10))
```


```{r}
p5 + theme_linedraw()
```



```{r}
p5 + theme_light()
```
```{r}
p5 + theme_minimal() +
  theme(text = element_text(color = "turquoise"))
```


```{r}
theme_new <- theme_bw() +
  theme(plot.background = element_rect(size = 1, color = "blue", fill = "black"),
        text=element_text(size = 12, family = "Serif", color = "ivory"),
        axis.text.y = element_text(colour = "purple"),
        axis.text.x = element_text(colour = "red"),
        panel.background = element_rect(fill = "pink"),
        strip.background = element_rect(fill = "orange"))

p5 + theme_new
```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```
```{r}

```


```{r}

```



```{r}

```





